-- migrations/000026_extend_session_stats.up.sql
ALTER TABLE session_statistics 
ADD COLUMN IF NOT EXISTS average_battery FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS minimum_battery FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS maximum_battery FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS average_temperature FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS minimum_temperature FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS maximum_temperature FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS distance_travelled FLOAT NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS device_participation_count INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS command_count INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS anomaly_count INT NOT NULL DEFAULT 0;
