apiVersion: v1
kind: ServiceAccount
metadata:
  name: core-service-sa
  namespace: argus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telemetry-service-sa
  namespace: argus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-sa
  namespace: argus
