services:
  core-service:
    volumes:
      - ../../certs:/certs:ro
    environment:
      - MINIO_USE_SSL=false
      - MINIO_ENDPOINT=minio:9000
      - ARGUS_MINIO_PUBLIC_HOST=172.17.0.1:9000

  minio:
    volumes: !reset
      - argus_minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-argus}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-arguspassword}
