package ai

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	EventsGeneratedTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "argus_ai_events_generated_total",
			Help: "Total number of semantic events generated by the AI runtime.",
		},
		[]string{"type", "severity"},
	)
	ReasoningLatencySeconds = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "argus_ai_reasoning_latency_seconds",
			Help:    "Latency of the LLM reasoning layer in seconds.",
			Buckets: []float64{0.1, 0.5, 1, 2, 5, 10, 30},
		},
		[]string{"provider"},
	)
	EmbeddingLatencySeconds = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "argus_ai_embedding_latency_seconds",
			Help:    "Latency of the embedding generation in seconds.",
			Buckets: []float64{0.01, 0.05, 0.1, 0.5, 1, 2},
		},
		[]string{"provider"},
	)
	IncidentsCreatedTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "argus_ai_incidents_created_total",
			Help: "Total number of incidents created by the correlation engine.",
		},
	)
	VectorQueriesTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "argus_ai_vector_queries_total",
			Help: "Total number of vector search queries performed.",
		},
		[]string{"table"},
	)
	LLMRequestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "argus_ai_llm_requests_total",
			Help: "Total number of LLM reasoning requests.",
		},
		[]string{"provider"},
	)
	LLMFailuresTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "argus_ai_llm_failures_total",
			Help: "Total number of LLM reasoning failures.",
		},
		[]string{"provider"},
	)
	QueriesTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "argus_ai_queries_total",
			Help: "Total number of AI queries processed by source type.",
		},
		[]string{"source"},
	)
	QueryFailuresTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "argus_ai_failures_total",
			Help: "Total number of AI query failures across all handlers.",
		},
	)
	QueryDurationSeconds = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "argus_ai_duration_seconds",
			Help:    "Latency of AI queries by source type in seconds.",
			Buckets: []float64{0.01, 0.05, 0.1, 0.5, 1, 2, 5, 10, 30},
		},
		[]string{"source"},
	)
	EmbeddingQueueDepth = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "argus_ai_embedding_queue_depth",
			Help: "Current depth of the embedding tasks queue.",
		},
	)
	EmbeddingSuccessesTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "argus_ai_embedding_successes_total",
			Help: "Total number of successful embedding tasks.",
		},
	)
	EmbeddingFailuresTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "argus_ai_embedding_failures_total",
			Help: "Total number of failed embedding tasks.",
		},
	)
	EmbeddingDroppedTasksTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "argus_ai_embedding_dropped_tasks_total",
			Help: "Total number of embedding tasks dropped due to queue saturation.",
		},
	)
	ReconciliationTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "argus_ai_embedding_reconciliation_total",
			Help: "Total number of background backfill reconciliation runs.",
		},
		[]string{"status"},
	)
	EmbedModelInfo = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "argus_ai_embed_model_info",
			Help: "Information about the loaded embedding model.",
		},
		[]string{"model", "dimension"},
	)
	EmbedRequestsTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "argus_ai_embed_requests_total",
			Help: "Total number of embedding requests.",
		},
	)
	EmbedDurationSeconds = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "argus_ai_embed_duration_seconds",
			Help:    "Latency of the embedding generation in seconds.",
			Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5},
		},
	)
	EmbedErrorsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "argus_ai_embed_errors_total",
			Help: "Total number of embedding request errors.",
		},
		[]string{"reason"},
	)
)
