import { FormEvent, useState, useMemo } from "react";
import { Plus, Trash2, Edit2, Save, X } from "lucide-react";
import { CopyableID, EmptyState, ErrorState, LoadingRows, PageHeader, Panel, StatusChip } from "../components/ui";
import { useAlerts, useRules, useUpdateRule } from "../hooks/useArgusData";
import { useWorkspaceContext } from "../context/WorkspaceContext";
import { compactID, formatDate } from "../lib/format";
import { api } from "../services/api";
import type { Rule } from "../types/api";

export function AlertsPage() {
  const { workspaceDevices } = useWorkspaceContext();
  const alerts = useAlerts();
  const rules = useRules();
  const updateRule = useUpdateRule();
  const [error, setError] = useState("");
  const [editRuleState, setEditRuleState] = useState<Rule | null>(null);

  const activeDeviceIds = useMemo(() => new Set(workspaceDevices.map(d => d.id)), [workspaceDevices]);

  const filteredAlerts = useMemo(() => {
    if (!alerts.data) return [];
    return alerts.data.filter(alert => activeDeviceIds.has(alert.device_id));
  }, [alerts.data, activeDeviceIds]);


  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");
    const formElement = event.currentTarget;
    const form = new FormData(formElement);
    const payload = {
      name: String(form.get("name") || ""),
      metric: String(form.get("metric") || ""),
      operator: String(form.get("operator") || ">"),
      threshold: Number(form.get("threshold") || 0),
      enabled: form.get("enabled") === "on"
    };

    try {
      if (editRuleState) {
        await updateRule.mutateAsync({ id: editRuleState.id, payload });
        setEditRuleState(null);
      } else {
        await api.rules.create(payload);
      }
      formElement.reset();
      await rules.refetch();
    } catch (err) {
      setError((err as Error).message);
    }
  }

  async function removeRule(id: string) {
    await api.rules.remove(id);
    await rules.refetch();
  }

  async function toggleRule(rule: Rule) {
    await updateRule.mutateAsync({ id: rule.id, payload: { enabled: !rule.enabled } });
  }

  return (
    <>
      <PageHeader eyebrow="Rules Engine" title="Automations" description="Manage telemetry threshold rules and review actual alerts generated by backend rule evaluation." />
      <div className="split">
        <Panel title="Alerts" subtitle="Recent system and device alerts">
          {alerts.isError ? <ErrorState message={(alerts.error as Error).message} onRetry={() => void alerts.refetch()} /> : (
            <div className="table-wrap">
              <table>
                <thead><tr><th>Alert</th><th>Device</th><th>Metric</th><th>Observed</th><th>Created</th></tr></thead>
                <tbody>
                  {alerts.isLoading && <LoadingRows rows={5} />}
                  {!alerts.isLoading && filteredAlerts.length === 0 && <tr><td colSpan={5}><EmptyState title="No alerts available" description="Alerts appear after ingested telemetry violates an enabled rule." /></td></tr>}
                  {filteredAlerts.map((alert) => (
                    <tr key={alert.id}>
                      <td><strong>{alert.message}</strong><div style={{ marginTop: 2 }}><CopyableID id={alert.id} /></div></td>
                      <td><CopyableID id={alert.device_id} /></td>
                      <td>{alert.metric} {alert.operator} {alert.threshold}</td>
                      <td>{alert.observed_value}</td>
                      <td>{formatDate(alert.created_at)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Panel>
        <div className="grid">
          <Panel title="Rules" subtitle="Configured alert threshold rules">
            {rules.isError ? <ErrorState message={(rules.error as Error).message} onRetry={() => void rules.refetch()} /> : (rules.data?.length ?? 0) === 0 && !rules.isLoading ? (
              <EmptyState title="No rules configured" description="Create a rule to evaluate incoming telemetry." />
            ) : (
              <div className="settings-list">
                {rules.data?.map((rule) => (
                  <div className="settings-row" key={rule.id}>
                    <div>
                      <strong>{rule.name}</strong>
                      <p className="muted">{rule.metric} {rule.operator} {rule.threshold}</p>
                    </div>
                    <div className="page-actions">
                      <button className="button compact secondary" onClick={() => void toggleRule(rule)} aria-label={`Toggle ${rule.name}`}>
                        <StatusChip value={rule.enabled ? "enabled" : "disabled"} />
                      </button>
                      <button className="button compact secondary" onClick={() => setEditRuleState(rule)} aria-label={`Edit ${rule.name}`}><Edit2 size={14} /></button>
                      <button className="button compact danger" onClick={() => void removeRule(rule.id)} aria-label={`Delete ${rule.name}`}><Trash2 size={14} /></button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </Panel>
          <Panel title={editRuleState ? "Update Rule" : "Create Rule"} subtitle={editRuleState ? "Modify the selected rule configurations" : "Define a new threshold condition"}>
            <form className="form-grid" onSubmit={onSubmit} key={editRuleState?.id || "create"}>
              <label className="field full"><span>Name</span><input name="name" defaultValue={editRuleState?.name || ""} required /></label>
              <label className="field"><span>Metric</span><input name="metric" defaultValue={editRuleState?.metric || ""} required /></label>
              <label className="field"><span>Operator</span><select name="operator" defaultValue={editRuleState?.operator || ">"}><option>&gt;</option><option>&gt;=</option><option>&lt;</option><option>&lt;=</option><option>==</option><option>!=</option></select></label>
              <label className="field"><span>Threshold</span><input name="threshold" type="number" step="any" defaultValue={editRuleState?.threshold ?? ""} required /></label>
              <label className="field"><span>Enabled</span><input name="enabled" type="checkbox" defaultChecked={editRuleState ? editRuleState.enabled : true} /></label>
              {error && <p className="muted field full">{error}</p>}
              <div className="field full page-actions" style={{ marginTop: "1rem" }}>
                <button className="button primary" type="submit" disabled={updateRule.isPending}>
                  {editRuleState ? <Save size={15} /> : <Plus size={15} />}
                  {editRuleState ? "Save Changes" : "Create Rule"}
                </button>
                {editRuleState && (
                  <button className="button secondary" type="button" onClick={() => setEditRuleState(null)}>
                    <X size={15} /> Cancel
                  </button>
                )}
              </div>
            </form>
          </Panel>
        </div>
      </div>
    </>
  );
}
