import { FormEvent, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { EmptyState, ErrorState, LoadingRows, PageHeader, Panel, StatusChip } from "../components/ui";
import { useAlerts, useRules } from "../hooks/useArgusData";
import { compactID, formatDate } from "../lib/format";
import { api } from "../services/api";

export function AlertsPage() {
  const alerts = useAlerts();
  const rules = useRules();
  const [error, setError] = useState("");

  async function createRule(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");
    const form = new FormData(event.currentTarget);
    try {
      await api.rules.create({
        name: String(form.get("name") || ""),
        metric: String(form.get("metric") || ""),
        operator: String(form.get("operator") || ">"),
        threshold: Number(form.get("threshold") || 0),
        enabled: form.get("enabled") === "on"
      });
      event.currentTarget.reset();
      await rules.refetch();
    } catch (err) {
      setError((err as Error).message);
    }
  }

  async function removeRule(id: string) {
    await api.rules.remove(id);
    await rules.refetch();
  }

  return (
    <>
      <PageHeader eyebrow="Rules Engine" title="Alerts" description="Manage telemetry threshold rules and review actual alerts generated by backend rule evaluation." />
      <div className="split">
        <Panel title="Alerts" subtitle="GET /alerts">
          {alerts.isError ? <ErrorState message={(alerts.error as Error).message} onRetry={() => void alerts.refetch()} /> : (
            <div className="table-wrap">
              <table>
                <thead><tr><th>Alert</th><th>Device</th><th>Metric</th><th>Observed</th><th>Created</th></tr></thead>
                <tbody>
                  {alerts.isLoading && <LoadingRows rows={5} />}
                  {!alerts.isLoading && (alerts.data?.length ?? 0) === 0 && <tr><td colSpan={5}><EmptyState title="No alerts available" description="Alerts appear after ingested telemetry violates an enabled rule." /></td></tr>}
                  {alerts.data?.map((alert) => (
                    <tr key={alert.id}>
                      <td><strong>{alert.message}</strong><div className="muted mono">{compactID(alert.id)}</div></td>
                      <td className="mono">{compactID(alert.device_id)}</td>
                      <td>{alert.metric} {alert.operator} {alert.threshold}</td>
                      <td>{alert.observed_value}</td>
                      <td>{formatDate(alert.created_at)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Panel>
        <div className="grid">
          <Panel title="Rules" subtitle="GET /rules">
            {rules.isError ? <ErrorState message={(rules.error as Error).message} onRetry={() => void rules.refetch()} /> : (rules.data?.length ?? 0) === 0 && !rules.isLoading ? (
              <EmptyState title="No rules configured" description="Create a rule to evaluate incoming telemetry." />
            ) : (
              <div className="settings-list">
                {rules.data?.map((rule) => (
                  <div className="settings-row" key={rule.id}>
                    <div>
                      <strong>{rule.name}</strong>
                      <p className="muted">{rule.metric} {rule.operator} {rule.threshold}</p>
                    </div>
                    <div className="page-actions">
                      <StatusChip value={rule.enabled ? "enabled" : "disabled"} />
                      <button className="button compact danger" onClick={() => void removeRule(rule.id)}><Trash2 size={14} /></button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </Panel>
          <Panel title="Create Rule" subtitle="POST /rules">
            <form className="form-grid" onSubmit={createRule}>
              <label className="field full"><span>Name</span><input name="name" required /></label>
              <label className="field"><span>Metric</span><input name="metric" required /></label>
              <label className="field"><span>Operator</span><select name="operator"><option>&gt;</option><option>&gt;=</option><option>&lt;</option><option>&lt;=</option><option>==</option><option>!=</option></select></label>
              <label className="field"><span>Threshold</span><input name="threshold" type="number" step="any" required /></label>
              <label className="field"><span>Enabled</span><input name="enabled" type="checkbox" defaultChecked /></label>
              {error && <p className="muted field full">{error}</p>}
              <button className="button primary" type="submit"><Plus size={15} />Create Rule</button>
            </form>
          </Panel>
        </div>
      </div>
    </>
  );
}
