// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.4
// source: shared/proto/telemetry/telemetry.proto

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TelemetryIntelligenceService_QueryAI_FullMethodName             = "/argus.telemetry.v1.TelemetryIntelligenceService/QueryAI"
	TelemetryIntelligenceService_GetSnapshot_FullMethodName         = "/argus.telemetry.v1.TelemetryIntelligenceService/GetSnapshot"
	TelemetryIntelligenceService_ListIncidents_FullMethodName       = "/argus.telemetry.v1.TelemetryIntelligenceService/ListIncidents"
	TelemetryIntelligenceService_FleetSummary_FullMethodName        = "/argus.telemetry.v1.TelemetryIntelligenceService/FleetSummary"
	TelemetryIntelligenceService_GetSessionTelemetry_FullMethodName = "/argus.telemetry.v1.TelemetryIntelligenceService/GetSessionTelemetry"
	TelemetryIntelligenceService_ConfigureRule_FullMethodName       = "/argus.telemetry.v1.TelemetryIntelligenceService/ConfigureRule"
	TelemetryIntelligenceService_ListRules_FullMethodName           = "/argus.telemetry.v1.TelemetryIntelligenceService/ListRules"
	TelemetryIntelligenceService_GetRulesWithAlerts_FullMethodName  = "/argus.telemetry.v1.TelemetryIntelligenceService/GetRulesWithAlerts"
	TelemetryIntelligenceService_ListEvents_FullMethodName          = "/argus.telemetry.v1.TelemetryIntelligenceService/ListEvents"
	TelemetryIntelligenceService_GetDeviceHistory_FullMethodName    = "/argus.telemetry.v1.TelemetryIntelligenceService/GetDeviceHistory"
	TelemetryIntelligenceService_DeleteRule_FullMethodName          = "/argus.telemetry.v1.TelemetryIntelligenceService/DeleteRule"
)

// TelemetryIntelligenceServiceClient is the client API for TelemetryIntelligenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryIntelligenceServiceClient interface {
	// Query AI for RAG queries and troubleshooting reasoning
	QueryAI(ctx context.Context, in *QueryAIRequest, opts ...grpc.CallOption) (*QueryAIResponse, error)
	// Retrieve consolidated telemetry and operational snapshot for a device
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*DeviceSnapshotResponse, error)
	// Get active incidents across a workspace or for a specific session
	ListIncidents(ctx context.Context, in *ListIncidentsRequest, opts ...grpc.CallOption) (*ListIncidentsResponse, error)
	// Get fleet-wide diagnostics summary for a workspace
	FleetSummary(ctx context.Context, in *FleetSummaryRequest, opts ...grpc.CallOption) (*FleetSummaryResponse, error)
	// Retrieve compiled telemetry aggregates, welford statistics, and incidents
	// for a session when it stops, and clean up Redis keys.
	GetSessionTelemetry(ctx context.Context, in *GetSessionTelemetryRequest, opts ...grpc.CallOption) (*SessionTelemetryResponse, error)
	// Coarse-grained Rule Configuration & Retrieval (combines CRUD into fewer APIs)
	ConfigureRule(ctx context.Context, in *ConfigureRuleRequest, opts ...grpc.CallOption) (*RuleResponse, error)
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	GetRulesWithAlerts(ctx context.Context, in *GetRulesWithAlertsRequest, opts ...grpc.CallOption) (*GetRulesWithAlertsResponse, error)
	// List historical operational events and logs
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	// Get operational memory history for a device
	GetDeviceHistory(ctx context.Context, in *GetDeviceHistoryRequest, opts ...grpc.CallOption) (*GetDeviceHistoryResponse, error)
	// Delete telemetry rule
	DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error)
}

type telemetryIntelligenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryIntelligenceServiceClient(cc grpc.ClientConnInterface) TelemetryIntelligenceServiceClient {
	return &telemetryIntelligenceServiceClient{cc}
}

func (c *telemetryIntelligenceServiceClient) QueryAI(ctx context.Context, in *QueryAIRequest, opts ...grpc.CallOption) (*QueryAIResponse, error) {
	out := new(QueryAIResponse)
	err := c.cc.Invoke(ctx, TelemetryIntelligenceService_QueryAI_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryIntelligenceServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*DeviceSnapshotResponse, error) {
	out := new(DeviceSnapshotResponse)
	err := c.cc.Invoke(ctx, TelemetryIntelligenceService_GetSnapshot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryIntelligenceServiceClient) ListIncidents(ctx context.Context, in *ListIncidentsRequest, opts ...grpc.CallOption) (*ListIncidentsResponse, error) {
	out := new(ListIncidentsResponse)
	err := c.cc.Invoke(ctx, TelemetryIntelligenceService_ListIncidents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryIntelligenceServiceClient) FleetSummary(ctx context.Context, in *FleetSummaryRequest, opts ...grpc.CallOption) (*FleetSummaryResponse, error) {
	out := new(FleetSummaryResponse)
	err := c.cc.Invoke(ctx, TelemetryIntelligenceService_FleetSummary_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryIntelligenceServiceClient) GetSessionTelemetry(ctx context.Context, in *GetSessionTelemetryRequest, opts ...grpc.CallOption) (*SessionTelemetryResponse, error) {
	out := new(SessionTelemetryResponse)
	err := c.cc.Invoke(ctx, TelemetryIntelligenceService_GetSessionTelemetry_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryIntelligenceServiceClient) ConfigureRule(ctx context.Context, in *ConfigureRuleRequest, opts ...grpc.CallOption) (*RuleResponse, error) {
	out := new(RuleResponse)
	err := c.cc.Invoke(ctx, TelemetryIntelligenceService_ConfigureRule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryIntelligenceServiceClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, TelemetryIntelligenceService_ListRules_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryIntelligenceServiceClient) GetRulesWithAlerts(ctx context.Context, in *GetRulesWithAlertsRequest, opts ...grpc.CallOption) (*GetRulesWithAlertsResponse, error) {
	out := new(GetRulesWithAlertsResponse)
	err := c.cc.Invoke(ctx, TelemetryIntelligenceService_GetRulesWithAlerts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryIntelligenceServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, TelemetryIntelligenceService_ListEvents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryIntelligenceServiceClient) GetDeviceHistory(ctx context.Context, in *GetDeviceHistoryRequest, opts ...grpc.CallOption) (*GetDeviceHistoryResponse, error) {
	out := new(GetDeviceHistoryResponse)
	err := c.cc.Invoke(ctx, TelemetryIntelligenceService_GetDeviceHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryIntelligenceServiceClient) DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error) {
	out := new(DeleteRuleResponse)
	err := c.cc.Invoke(ctx, TelemetryIntelligenceService_DeleteRule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryIntelligenceServiceServer is the server API for TelemetryIntelligenceService service.
// All implementations must embed UnimplementedTelemetryIntelligenceServiceServer
// for forward compatibility
type TelemetryIntelligenceServiceServer interface {
	// Query AI for RAG queries and troubleshooting reasoning
	QueryAI(context.Context, *QueryAIRequest) (*QueryAIResponse, error)
	// Retrieve consolidated telemetry and operational snapshot for a device
	GetSnapshot(context.Context, *GetSnapshotRequest) (*DeviceSnapshotResponse, error)
	// Get active incidents across a workspace or for a specific session
	ListIncidents(context.Context, *ListIncidentsRequest) (*ListIncidentsResponse, error)
	// Get fleet-wide diagnostics summary for a workspace
	FleetSummary(context.Context, *FleetSummaryRequest) (*FleetSummaryResponse, error)
	// Retrieve compiled telemetry aggregates, welford statistics, and incidents
	// for a session when it stops, and clean up Redis keys.
	GetSessionTelemetry(context.Context, *GetSessionTelemetryRequest) (*SessionTelemetryResponse, error)
	// Coarse-grained Rule Configuration & Retrieval (combines CRUD into fewer APIs)
	ConfigureRule(context.Context, *ConfigureRuleRequest) (*RuleResponse, error)
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	GetRulesWithAlerts(context.Context, *GetRulesWithAlertsRequest) (*GetRulesWithAlertsResponse, error)
	// List historical operational events and logs
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	// Get operational memory history for a device
	GetDeviceHistory(context.Context, *GetDeviceHistoryRequest) (*GetDeviceHistoryResponse, error)
	// Delete telemetry rule
	DeleteRule(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error)
	mustEmbedUnimplementedTelemetryIntelligenceServiceServer()
}

// UnimplementedTelemetryIntelligenceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTelemetryIntelligenceServiceServer struct {
}

func (UnimplementedTelemetryIntelligenceServiceServer) QueryAI(context.Context, *QueryAIRequest) (*QueryAIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAI not implemented")
}
func (UnimplementedTelemetryIntelligenceServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*DeviceSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedTelemetryIntelligenceServiceServer) ListIncidents(context.Context, *ListIncidentsRequest) (*ListIncidentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIncidents not implemented")
}
func (UnimplementedTelemetryIntelligenceServiceServer) FleetSummary(context.Context, *FleetSummaryRequest) (*FleetSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FleetSummary not implemented")
}
func (UnimplementedTelemetryIntelligenceServiceServer) GetSessionTelemetry(context.Context, *GetSessionTelemetryRequest) (*SessionTelemetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionTelemetry not implemented")
}
func (UnimplementedTelemetryIntelligenceServiceServer) ConfigureRule(context.Context, *ConfigureRuleRequest) (*RuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureRule not implemented")
}
func (UnimplementedTelemetryIntelligenceServiceServer) ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedTelemetryIntelligenceServiceServer) GetRulesWithAlerts(context.Context, *GetRulesWithAlertsRequest) (*GetRulesWithAlertsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRulesWithAlerts not implemented")
}
func (UnimplementedTelemetryIntelligenceServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedTelemetryIntelligenceServiceServer) GetDeviceHistory(context.Context, *GetDeviceHistoryRequest) (*GetDeviceHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceHistory not implemented")
}
func (UnimplementedTelemetryIntelligenceServiceServer) DeleteRule(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRule not implemented")
}
func (UnimplementedTelemetryIntelligenceServiceServer) mustEmbedUnimplementedTelemetryIntelligenceServiceServer() {
}

// UnsafeTelemetryIntelligenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryIntelligenceServiceServer will
// result in compilation errors.
type UnsafeTelemetryIntelligenceServiceServer interface {
	mustEmbedUnimplementedTelemetryIntelligenceServiceServer()
}

func RegisterTelemetryIntelligenceServiceServer(s grpc.ServiceRegistrar, srv TelemetryIntelligenceServiceServer) {
	s.RegisterService(&TelemetryIntelligenceService_ServiceDesc, srv)
}

func _TelemetryIntelligenceService_QueryAI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryIntelligenceServiceServer).QueryAI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryIntelligenceService_QueryAI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryIntelligenceServiceServer).QueryAI(ctx, req.(*QueryAIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryIntelligenceService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryIntelligenceServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryIntelligenceService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryIntelligenceServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryIntelligenceService_ListIncidents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIncidentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryIntelligenceServiceServer).ListIncidents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryIntelligenceService_ListIncidents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryIntelligenceServiceServer).ListIncidents(ctx, req.(*ListIncidentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryIntelligenceService_FleetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FleetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryIntelligenceServiceServer).FleetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryIntelligenceService_FleetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryIntelligenceServiceServer).FleetSummary(ctx, req.(*FleetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryIntelligenceService_GetSessionTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryIntelligenceServiceServer).GetSessionTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryIntelligenceService_GetSessionTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryIntelligenceServiceServer).GetSessionTelemetry(ctx, req.(*GetSessionTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryIntelligenceService_ConfigureRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryIntelligenceServiceServer).ConfigureRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryIntelligenceService_ConfigureRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryIntelligenceServiceServer).ConfigureRule(ctx, req.(*ConfigureRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryIntelligenceService_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryIntelligenceServiceServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryIntelligenceService_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryIntelligenceServiceServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryIntelligenceService_GetRulesWithAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRulesWithAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryIntelligenceServiceServer).GetRulesWithAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryIntelligenceService_GetRulesWithAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryIntelligenceServiceServer).GetRulesWithAlerts(ctx, req.(*GetRulesWithAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryIntelligenceService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryIntelligenceServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryIntelligenceService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryIntelligenceServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryIntelligenceService_GetDeviceHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryIntelligenceServiceServer).GetDeviceHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryIntelligenceService_GetDeviceHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryIntelligenceServiceServer).GetDeviceHistory(ctx, req.(*GetDeviceHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryIntelligenceService_DeleteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryIntelligenceServiceServer).DeleteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryIntelligenceService_DeleteRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryIntelligenceServiceServer).DeleteRule(ctx, req.(*DeleteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryIntelligenceService_ServiceDesc is the grpc.ServiceDesc for TelemetryIntelligenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryIntelligenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.telemetry.v1.TelemetryIntelligenceService",
	HandlerType: (*TelemetryIntelligenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryAI",
			Handler:    _TelemetryIntelligenceService_QueryAI_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _TelemetryIntelligenceService_GetSnapshot_Handler,
		},
		{
			MethodName: "ListIncidents",
			Handler:    _TelemetryIntelligenceService_ListIncidents_Handler,
		},
		{
			MethodName: "FleetSummary",
			Handler:    _TelemetryIntelligenceService_FleetSummary_Handler,
		},
		{
			MethodName: "GetSessionTelemetry",
			Handler:    _TelemetryIntelligenceService_GetSessionTelemetry_Handler,
		},
		{
			MethodName: "ConfigureRule",
			Handler:    _TelemetryIntelligenceService_ConfigureRule_Handler,
		},
		{
			MethodName: "ListRules",
			Handler:    _TelemetryIntelligenceService_ListRules_Handler,
		},
		{
			MethodName: "GetRulesWithAlerts",
			Handler:    _TelemetryIntelligenceService_GetRulesWithAlerts_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _TelemetryIntelligenceService_ListEvents_Handler,
		},
		{
			MethodName: "GetDeviceHistory",
			Handler:    _TelemetryIntelligenceService_GetDeviceHistory_Handler,
		},
		{
			MethodName: "DeleteRule",
			Handler:    _TelemetryIntelligenceService_DeleteRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/proto/telemetry/telemetry.proto",
}
