package ai

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	EventsGeneratedTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "argus_ai_events_generated_total",
			Help: "Total number of semantic events generated by the AI runtime.",
		},
		[]string{"type", "severity"},
	)
	ReasoningLatencySeconds = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "argus_ai_reasoning_latency_seconds",
			Help:    "Latency of the LLM reasoning layer in seconds.",
			Buckets: []float64{0.5, 1, 2, 5, 10, 30},
		},
	)
	EmbeddingLatencySeconds = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "argus_ai_embedding_latency_seconds",
			Help:    "Latency of the embedding generation in seconds.",
			Buckets: []float64{0.01, 0.05, 0.1, 0.5, 1, 2},
		},
	)
	IncidentsCreatedTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "argus_ai_incidents_created_total",
			Help: "Total number of incidents created by the correlation engine.",
		},
	)
	LLMFailuresTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "argus_ai_llm_failures_total",
			Help: "Total number of LLM reasoning failures.",
		},
	)
)
