name=ArgusSDK
version=1.0.0
author=Argus IoT
maintainer=Argus IoT
sentence=ARGUS ESP32 IoT SDK
paragraph=Provides WiFi, MQTT, TLS, HTTP, OTA, rollback, and diagnostics for ARGUS-managed ESP32 devices.
layout=recursive
category=Communication
url=https://github.com/vishalss1/argus
architectures=esp32
depends=PubSubClient, ArduinoJson
includes=argus.h,argus_config.h
