// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.4
// source: shared/proto/core/core.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CoreService_GetDeviceContext_FullMethodName    = "/argus.core.v1.CoreService/GetDeviceContext"
	CoreService_ExecuteCommand_FullMethodName      = "/argus.core.v1.CoreService/ExecuteCommand"
	CoreService_GetPolicy_FullMethodName           = "/argus.core.v1.CoreService/GetPolicy"
	CoreService_RecordExecution_FullMethodName     = "/argus.core.v1.CoreService/RecordExecution"
	CoreService_GetWorkspaceDevices_FullMethodName = "/argus.core.v1.CoreService/GetWorkspaceDevices"
)

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreServiceClient interface {
	// Coarse-grained endpoint to retrieve all context about a device for rule/AI analysis.
	// Combines device registry, workspace membership, active session status, policy configuration, and usage plans.
	GetDeviceContext(ctx context.Context, in *GetDeviceContextRequest, opts ...grpc.CallOption) (*DeviceContextResponse, error)
	// Coarse-grained endpoint to execute commands on devices (e.g. reboot, config update)
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
	// Coarse-grained endpoint to check and retrieve remediation policies for a given action and device.
	GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error)
	// Coarse-grained endpoint to record or update execution of action/policy
	RecordExecution(ctx context.Context, in *RecordExecutionRequest, opts ...grpc.CallOption) (*RecordExecutionResponse, error)
	// Retrieve all device IDs belonging to a workspace
	GetWorkspaceDevices(ctx context.Context, in *GetWorkspaceDevicesRequest, opts ...grpc.CallOption) (*GetWorkspaceDevicesResponse, error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) GetDeviceContext(ctx context.Context, in *GetDeviceContextRequest, opts ...grpc.CallOption) (*DeviceContextResponse, error) {
	out := new(DeviceContextResponse)
	err := c.cc.Invoke(ctx, CoreService_GetDeviceContext_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	out := new(ExecuteCommandResponse)
	err := c.cc.Invoke(ctx, CoreService_ExecuteCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*PolicyResponse, error) {
	out := new(PolicyResponse)
	err := c.cc.Invoke(ctx, CoreService_GetPolicy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) RecordExecution(ctx context.Context, in *RecordExecutionRequest, opts ...grpc.CallOption) (*RecordExecutionResponse, error) {
	out := new(RecordExecutionResponse)
	err := c.cc.Invoke(ctx, CoreService_RecordExecution_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetWorkspaceDevices(ctx context.Context, in *GetWorkspaceDevicesRequest, opts ...grpc.CallOption) (*GetWorkspaceDevicesResponse, error) {
	out := new(GetWorkspaceDevicesResponse)
	err := c.cc.Invoke(ctx, CoreService_GetWorkspaceDevices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServiceServer is the server API for CoreService service.
// All implementations must embed UnimplementedCoreServiceServer
// for forward compatibility
type CoreServiceServer interface {
	// Coarse-grained endpoint to retrieve all context about a device for rule/AI analysis.
	// Combines device registry, workspace membership, active session status, policy configuration, and usage plans.
	GetDeviceContext(context.Context, *GetDeviceContextRequest) (*DeviceContextResponse, error)
	// Coarse-grained endpoint to execute commands on devices (e.g. reboot, config update)
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	// Coarse-grained endpoint to check and retrieve remediation policies for a given action and device.
	GetPolicy(context.Context, *GetPolicyRequest) (*PolicyResponse, error)
	// Coarse-grained endpoint to record or update execution of action/policy
	RecordExecution(context.Context, *RecordExecutionRequest) (*RecordExecutionResponse, error)
	// Retrieve all device IDs belonging to a workspace
	GetWorkspaceDevices(context.Context, *GetWorkspaceDevicesRequest) (*GetWorkspaceDevicesResponse, error)
	mustEmbedUnimplementedCoreServiceServer()
}

// UnimplementedCoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCoreServiceServer struct {
}

func (UnimplementedCoreServiceServer) GetDeviceContext(context.Context, *GetDeviceContextRequest) (*DeviceContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceContext not implemented")
}
func (UnimplementedCoreServiceServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedCoreServiceServer) GetPolicy(context.Context, *GetPolicyRequest) (*PolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPolicy not implemented")
}
func (UnimplementedCoreServiceServer) RecordExecution(context.Context, *RecordExecutionRequest) (*RecordExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordExecution not implemented")
}
func (UnimplementedCoreServiceServer) GetWorkspaceDevices(context.Context, *GetWorkspaceDevicesRequest) (*GetWorkspaceDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkspaceDevices not implemented")
}
func (UnimplementedCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_GetDeviceContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetDeviceContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetDeviceContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetDeviceContext(ctx, req.(*GetDeviceContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetPolicy(ctx, req.(*GetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_RecordExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).RecordExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_RecordExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).RecordExecution(ctx, req.(*RecordExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetWorkspaceDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkspaceDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetWorkspaceDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetWorkspaceDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetWorkspaceDevices(ctx, req.(*GetWorkspaceDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.core.v1.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceContext",
			Handler:    _CoreService_GetDeviceContext_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _CoreService_ExecuteCommand_Handler,
		},
		{
			MethodName: "GetPolicy",
			Handler:    _CoreService_GetPolicy_Handler,
		},
		{
			MethodName: "RecordExecution",
			Handler:    _CoreService_RecordExecution_Handler,
		},
		{
			MethodName: "GetWorkspaceDevices",
			Handler:    _CoreService_GetWorkspaceDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/proto/core/core.proto",
}
